- name: installing cart component 
  hosts: cart
  become: yes  
  tasks:
  - name: setup nodejs repo
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs 
      state: installed

  - name: check roboshop cart exist or not
    # when you want to run linux commands directly i.e in the case ansible module not available
    # when the cart does not exists, ansible treating this failure and comeout by default
    # ignore_errors: true
    ansible.builtin.command: id roboshop
    register: out #output is variable name
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{out}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{out.rc}}"
  - when: out.rc != 0
    name: create cart roboshop
    become: yes # we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop
     #if this expression is true then only this module will run
  - name: check /app exist or not
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: print directory status
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - name: create directory if not exists
    ansible.builtin.file:
      path: /app
      state: directory
      mode: "0755"
    when: directory.stat.exists == False

  - name: downloading cart code
    ansible.builtin.get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: extract the code in cart zip file to /app folder
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: isntalling npm dependencies
    ansible.builtin.shell: npm install
    args:
      chdir: /app

  - name: creating a service and copy
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: reload the daemon
    ansible.builtin.systemd:
      name: cart
      state: restarted
      daemon_reload: true

  - name: restart cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: true
  


  