- name: installing catalogue component 
  hosts: catalogue
  become: yes  
  tasks:
  - name: setup nodejs repo
    ansible.builtin.command: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs 
      state: installed
 