- name: Install Redis component
  hosts: redis
  become: yes
  tasks:
  - name: Install the latest version of redis
    ansible.builtin.dnf:
      name: redis
      state: installed

  - name: Allow remote connections to redis
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes